// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ess_cpp
double ess_cpp(const arma::vec& x);
RcppExport SEXP _dgtf_ess_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ess_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// split_rhat_cpp
double split_rhat_cpp(const arma::mat& X);
RcppExport SEXP _dgtf_split_rhat_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(split_rhat_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// lognorm2serial
Rcpp::NumericVector lognorm2serial(const double& mu, const double& sd2);
RcppExport SEXP _dgtf_lognorm2serial(SEXP muSEXP, SEXP sd2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type sd2(sd2SEXP);
    rcpp_result_gen = Rcpp::wrap(lognorm2serial(mu, sd2));
    return rcpp_result_gen;
END_RCPP
}
// serial2lognorm
Rcpp::NumericVector serial2lognorm(const double& m, const double& s2);
RcppExport SEXP _dgtf_serial2lognorm(SEXP mSEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double& >::type m(mSEXP);
    Rcpp::traits::input_parameter< const double& >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(serial2lognorm(m, s2));
    return rcpp_result_gen;
END_RCPP
}
// dnbinom0
Rcpp::NumericVector dnbinom0(const unsigned int& nL, const double& kappa, const double& r);
RcppExport SEXP _dgtf_dnbinom0(SEXP nLSEXP, SEXP kappaSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const unsigned int& >::type nL(nLSEXP);
    Rcpp::traits::input_parameter< const double& >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< const double& >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(dnbinom0(nL, kappa, r));
    return rcpp_result_gen;
END_RCPP
}
// dlognorm0
Rcpp::NumericVector dlognorm0(const unsigned int& nL, const double& mu, const double& sd2);
RcppExport SEXP _dgtf_dlognorm0(SEXP nLSEXP, SEXP muSEXP, SEXP sd2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const unsigned int& >::type nL(nLSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type sd2(sd2SEXP);
    rcpp_result_gen = Rcpp::wrap(dlognorm0(nL, mu, sd2));
    return rcpp_result_gen;
END_RCPP
}
// dgtf_default_algo_settings
Rcpp::List dgtf_default_algo_settings(const std::string& method);
RcppExport SEXP _dgtf_dgtf_default_algo_settings(SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(dgtf_default_algo_settings(method));
    return rcpp_result_gen;
END_RCPP
}
// dgtf_default_model
Rcpp::List dgtf_default_model();
RcppExport SEXP _dgtf_dgtf_default_model() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(dgtf_default_model());
    return rcpp_result_gen;
END_RCPP
}
// dgtf_simulate
Rcpp::List dgtf_simulate(const Rcpp::List& settings, const unsigned int& ntime, const double& y0, const Rcpp::Nullable<Rcpp::NumericVector>& z);
RcppExport SEXP _dgtf_dgtf_simulate(SEXP settingsSEXP, SEXP ntimeSEXP, SEXP y0SEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type settings(settingsSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type ntime(ntimeSEXP);
    Rcpp::traits::input_parameter< const double& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericVector>& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(dgtf_simulate(settings, ntime, y0, z));
    return rcpp_result_gen;
END_RCPP
}
// dgtf_infer
Rcpp::List dgtf_infer(const Rcpp::List& model_settings, const arma::vec& y_in, const std::string& method, const Rcpp::List& method_settings, const Rcpp::Nullable<Rcpp::NumericMatrix>& X, const bool& add_y0);
RcppExport SEXP _dgtf_dgtf_infer(SEXP model_settingsSEXP, SEXP y_inSEXP, SEXP methodSEXP, SEXP method_settingsSEXP, SEXP XSEXP, SEXP add_y0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model_settings(model_settingsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_in(y_inSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type method_settings(method_settingsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericMatrix>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const bool& >::type add_y0(add_y0SEXP);
    rcpp_result_gen = Rcpp::wrap(dgtf_infer(model_settings, y_in, method, method_settings, X, add_y0));
    return rcpp_result_gen;
END_RCPP
}
// dgtf_posterior_predictive
Rcpp::List dgtf_posterior_predictive(const Rcpp::List& output, const Rcpp::List& model_opts, const arma::vec& y, const unsigned int& nrep, const Rcpp::Nullable<Rcpp::NumericVector>& Rt, const double& level);
RcppExport SEXP _dgtf_dgtf_posterior_predictive(SEXP outputSEXP, SEXP model_optsSEXP, SEXP ySEXP, SEXP nrepSEXP, SEXP RtSEXP, SEXP levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type output(outputSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model_opts(model_optsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericVector>& >::type Rt(RtSEXP);
    Rcpp::traits::input_parameter< const double& >::type level(levelSEXP);
    rcpp_result_gen = Rcpp::wrap(dgtf_posterior_predictive(output, model_opts, y, nrep, Rt, level));
    return rcpp_result_gen;
END_RCPP
}
// dgtf_forecast
Rcpp::List dgtf_forecast(const Rcpp::List& output, const Rcpp::List& model_settings, const arma::vec& y, const unsigned int nrep, const unsigned int& k, const Rcpp::Nullable<Rcpp::NumericVector>& ypred_true, const bool& only_evaluate_last_one, const bool& return_all_samples);
RcppExport SEXP _dgtf_dgtf_forecast(SEXP outputSEXP, SEXP model_settingsSEXP, SEXP ySEXP, SEXP nrepSEXP, SEXP kSEXP, SEXP ypred_trueSEXP, SEXP only_evaluate_last_oneSEXP, SEXP return_all_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type output(outputSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type model_settings(model_settingsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< const unsigned int& >::type k(kSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Rcpp::NumericVector>& >::type ypred_true(ypred_trueSEXP);
    Rcpp::traits::input_parameter< const bool& >::type only_evaluate_last_one(only_evaluate_last_oneSEXP);
    Rcpp::traits::input_parameter< const bool& >::type return_all_samples(return_all_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(dgtf_forecast(output, model_settings, y, nrep, k, ypred_true, only_evaluate_last_one, return_all_samples));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dgtf_ess_cpp", (DL_FUNC) &_dgtf_ess_cpp, 1},
    {"_dgtf_split_rhat_cpp", (DL_FUNC) &_dgtf_split_rhat_cpp, 1},
    {"_dgtf_lognorm2serial", (DL_FUNC) &_dgtf_lognorm2serial, 2},
    {"_dgtf_serial2lognorm", (DL_FUNC) &_dgtf_serial2lognorm, 2},
    {"_dgtf_dnbinom0", (DL_FUNC) &_dgtf_dnbinom0, 3},
    {"_dgtf_dlognorm0", (DL_FUNC) &_dgtf_dlognorm0, 3},
    {"_dgtf_dgtf_default_algo_settings", (DL_FUNC) &_dgtf_dgtf_default_algo_settings, 1},
    {"_dgtf_dgtf_default_model", (DL_FUNC) &_dgtf_dgtf_default_model, 0},
    {"_dgtf_dgtf_simulate", (DL_FUNC) &_dgtf_dgtf_simulate, 4},
    {"_dgtf_dgtf_infer", (DL_FUNC) &_dgtf_dgtf_infer, 6},
    {"_dgtf_dgtf_posterior_predictive", (DL_FUNC) &_dgtf_dgtf_posterior_predictive, 6},
    {"_dgtf_dgtf_forecast", (DL_FUNC) &_dgtf_dgtf_forecast, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_dgtf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
