# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ess_cpp <- function(x) {
    .Call(`_dgtf_ess_cpp`, x)
}

split_rhat_cpp <- function(X) {
    .Call(`_dgtf_split_rhat_cpp`, X)
}

#' @export
lognorm2serial <- function(mu, sd2) {
    .Call(`_dgtf_lognorm2serial`, mu, sd2)
}

#' @export
serial2lognorm <- function(m, s2) {
    .Call(`_dgtf_serial2lognorm`, m, s2)
}

#' @export
dnbinom0 <- function(nL, kappa, r) {
    .Call(`_dgtf_dnbinom0`, nL, kappa, r)
}

#' @export
dlognorm0 <- function(nL, mu, sd2) {
    .Call(`_dgtf_dlognorm0`, nL, mu, sd2)
}

#' @export
dgtf_default_algo_settings <- function(method) {
    .Call(`_dgtf_dgtf_default_algo_settings`, method)
}

#' @export
dgtf_default_model <- function() {
    .Call(`_dgtf_dgtf_default_model`)
}

#' @export
dgtf_simulate <- function(settings, ntime, y0 = 0., z = NULL) {
    .Call(`_dgtf_dgtf_simulate`, settings, ntime, y0, z)
}

#' @export
dgtf_infer <- function(model_settings, y_in, method, method_settings, X = NULL, add_y0 = FALSE) {
    .Call(`_dgtf_dgtf_infer`, model_settings, y_in, method, method_settings, X, add_y0)
}

#' @export
dgtf_posterior_predictive <- function(output, model_opts, y, nrep = 0L, Rt = NULL, level = 0.95) {
    .Call(`_dgtf_dgtf_posterior_predictive`, output, model_opts, y, nrep, Rt, level)
}

#' @export
dgtf_forecast <- function(output, model_settings, y, nrep = 100L, k = 1L, ypred_true = NULL, only_evaluate_last_one = FALSE, return_all_samples = FALSE) {
    .Call(`_dgtf_dgtf_forecast`, output, model_settings, y, nrep, k, ypred_true, only_evaluate_last_one, return_all_samples)
}

